Rust test & Mutliversx 0.38.0
gfusee/sc-tuto-flip-rs pull request #2
Opened 2023-01-05 15:22 UTC by AtoMiiKGreg

Wrote some tests in RTF 
Upgraded SC to Multiverx 0.38.0
Added a closure to update token_reserve storage after the withdraw

2023-01-06 11:57 UTC, gfusee commented
putting .idea is useless if you have no run configurations

2023-01-06 12:14 UTC, gfusee commented
il y a des tests mandos qui ne passent pas

2023-01-06 13:54 UTC, AtoMiiKGreg commented
.idea supprimé & tests mandos corrigés

2023-01-10 10:48 UTC, gfusee requested changes

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +        &self) {
si tu vas à la ligne après increase_reserve( alors tu peux mettre la parenthèse après le &self sur une nouvelle ligne aussi

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +        let (payment_token,payment_nonce,payment_amount) = self.call_value().egld_or_single_esdt().into_tuple();
rajoute des espaces après les virgules pour aérer le code

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +        amount: OptionalValue<BigUint<Self::Api>>
c'est une nouvelle feature le amount optionel, l'idée est bonne il faudrait juste rajouter un test RTF ou mandos (pour EGLD et ESDT) qui vérifie que ça fonctionne bien quand on passe None

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +        let reserve_mapper = self.token_reserve(&token_identifier,token_nonce).get();
espace après la virgule comme plus haut

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +            OptionalValue::Some(amt)=>amt,
espace entre le Some(...) et le amt comme tu as fait pour le cas None la ligne du dessous

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +            "Invalid withdraw amount");
tu peux mettre la parenthèse de fin sur une nouvelle ligne stp?

2023-01-10 10:48 UTC, gfusee commented on src/admin.rs
> +                &withdraw_amount);
pareil la parenthèse sur une nouvelle ligne

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +    #[endpoint(flip)]
pas besoin de préciser (flip) quand le nom de la fonction est le même

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +        let (token_id, nonce,payment_amount ) = self.call_value().egld_or_single_esdt().into_tuple();
espace après la virgule qui suit nonce

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +                0,
nonce au lieu de 0

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +                &owner_profits);
parenthèse sur une nouvelle ligne

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +                &flip.bounty);
parenthèse sur une nouvelle ligne

2023-01-10 10:48 UTC, gfusee commented on src/lib.rs
> +                    &profit_if_win);
parenthèse sur une nouvelle ligne

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    let amount:u64 = 200;
amount = 200 ? dans un commentaire sur un autre fichier tu dis vouloir increase_reserve de 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +            let expected_reserve = managed_biguint!(200);
utilise la variable amount ici

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +        .execute_query(&setup.contract_wrapper,|sc|{
espace après la virgule

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +            let actual_reserve= sc.token_reserve(&managed_egld_token_id!(),0).get();
espace avant le =

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,200).assert_ok();
espace après la virgule

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID,200).assert_ok();
pareil

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,200).assert_ok();
tu utilises 200, pourquoi ne pas avoir une variable commune?

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +        ).assert_ok();
le .assert_ok tu peux le mettre sur une nouvelle ligne vu que tu l'as aussi fait + haut

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +            println!("{:?}", actual_reserve);
println! n'a pas d'intérêt, je pense que tu as oublié de l'enlever après avoir debug

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +            println!("{:?}", expected_reserve)
pareil

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +fn withdraw_reserve() {
tu tests ici EGLD et ESDT, tu peux séparer ce test en deux tests plus petits : le premier pour EGLD et le second pour ESDT

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +                let expected = managed_biguint!(10);
tu utilises deux fois 10 dans ce test, tu peux le mettre dans une variable

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +                let expected = 2u64;
tu utilises deux fois 2 dans ce test, tu peux le mettre dans une variable

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,100).assert_ok();
si tu changes les autres 200 en 100, ça peut être intéressant de mettre cette valeur dans une variable globale

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID,100).assert_ok();
même remarque pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID,100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    fn multiple_flip_bounty_err(){
ton indentation est cassée

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID, 100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID, 100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID,100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,100).assert_ok();
même remarque que plus haut pour le 100

2023-01-10 10:48 UTC, gfusee commented on mandos/bounty_single_lose_usdc.scen.json
> -                        "str:token_reserve|nested:str:USDC-abcdef|u64:1": "100,094,000",
étant donné qu'on a pas de tests avec un nonce != 0 ça serait bien de laisser le nonce de l'USDC à 1 dans mandos

2023-01-10 11:25 UTC, AtoMiiKGreg commented on src/admin.rs
> +        &self) {
j'ai remonté &self. merci

2023-01-10 11:26 UTC, AtoMiiKGreg commented on src/admin.rs
> +        let (payment_token,payment_nonce,payment_amount) = self.call_value().egld_or_single_esdt().into_tuple();
Je fais ça merci

2023-01-10 11:28 UTC, AtoMiiKGreg commented on src/admin.rs
> +        let reserve_mapper = self.token_reserve(&token_identifier,token_nonce).get();
fait Merci

2023-01-10 11:29 UTC, AtoMiiKGreg commented on src/admin.rs
> +            OptionalValue::Some(amt)=>amt,
Fait merci

2023-01-10 11:31 UTC, AtoMiiKGreg commented on src/admin.rs
> +            "Invalid withdraw amount");
Bien sûr

2023-01-10 11:32 UTC, AtoMiiKGreg commented on src/admin.rs
> +                &withdraw_amount);
Fait merci

2023-01-10 11:32 UTC, AtoMiiKGreg commented on src/lib.rs
> +    #[endpoint(flip)]
Ah interessant je savais pas merci

2023-01-10 11:34 UTC, GregDev13 commented on src/lib.rs
> +        let (token_id, nonce,payment_amount ) = self.call_value().egld_or_single_esdt().into_tuple();
Fait merci

2023-01-10 11:34 UTC, AtoMiiKGreg commented on src/lib.rs
> +                &owner_profits);
Fait merci

2023-01-10 11:35 UTC, AtoMiiKGreg commented on src/lib.rs
> +                &flip.bounty);
Fait merci

2023-01-10 11:35 UTC, AtoMiiKGreg commented on src/lib.rs
> +                    &profit_if_win);
Fait merci

2023-01-10 11:43 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    let amount:u64 = 200;
Ah oui cela prête à confusion j'increase_reserve de 100 dans tout mes autres test mais pas dans le test unitaire de la fonction increase_reserve. Je change cela de suite. merci

2023-01-10 11:44 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +            let expected_reserve = managed_biguint!(200);
Fait merci

2023-01-10 11:45 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +        .execute_query(&setup.contract_wrapper,|sc|{
Fait merci

2023-01-10 11:45 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +            let actual_reserve= sc.token_reserve(&managed_egld_token_id!(),0).get();
Fait merci

2023-01-10 11:45 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,200).assert_ok();
Fait merci

2023-01-10 11:46 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&FLIP_TOKEN_ID,200).assert_ok();
Fait merci

2023-01-10 11:48 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,200).assert_ok();
Je viens de la créer tu as raison. merci

2023-01-10 11:52 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +            println!("{:?}", actual_reserve);
hihi oups

2023-01-10 11:55 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +                let expected = managed_biguint!(10);
Créer merci

2023-01-10 11:57 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +                let expected = 2u64;
Fait merci

2023-01-10 12:04 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    fn multiple_flip_bounty_err(){
Bien vu

2023-01-10 13:11 UTC, AtoMiiKGreg commented on tests/flip_rust_test.rs
> +    setup.increase_reserve(&EGLD_TOKEN_ID,100).assert_ok();
Fait Merci

2023-01-10 15:00 UTC, AtoMiiKGreg commented on src/admin.rs
> +        amount: OptionalValue<BigUint<Self::Api>>
Tests rajoutés dans les withdraw EGLD et ESDT

2023-01-10 15:16 UTC, GregDev13 commented on src/lib.rs
> +                0,
Fait Merci

2023-01-10 16:18 UTC, AtoMiiKGreg commented on mandos/bounty_single_lose_usdc.scen.json
> -                        "str:token_reserve|nested:str:USDC-abcdef|u64:1": "100,094,000",
nonce à 1 et usdc changé en tokn

2023-01-10 16:19 UTC, AtoMiiKGreg commented
Modifications faites

2023-01-16 14:02 UTC, gfusee commented on src/admin.rs
> +                0,
attention il faut utiliser token_nonce ici sinon tu auras des problèmes sur les ESDT qui ne sont pas fongibles

2023-01-16 14:14 UTC, AtoMiiKGreg commented on src/admin.rs
> +                0,
Merci

2023-01-16 14:16 UTC, merged

2023-01-16 14:17 UTC, gfusee commented
merci beaucoup pour ton travail @AtoMiiKGreg 🙌

2023-01-16 14:20 UTC, AtoMiiKGreg commented
Merci je suis si fier d'avoir apporté ma contribution. Un très très grand merci à toi 😍